# fly.toml app configuration file generated for slavbros-content on 2025-04-08T15:05:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'slavbros-content'
primary_region = 'mad'

[build]

[env]
  DATABASE_CLIENT = 'sqlite'
  DATABASE_FILENAME = '/public/uploads/data/strapi.db'
  
[[mounts]]
  source = 'cms_data'
  destination = '/public/uploads'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
